services:
  adventurebot:
    image: techblog/adventurebot:latest
    container_name: adventurebot
    restart: unless-stopped
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      AL_URL: ${AL_URL}
      AL_USERNAME: ${AL_USERNAME}
      AL_PASSWORD: ${AL_PASSWORD}
      ALLOWED_IDS: ${ALLOWED_IDS:-}
    volumes:
      - ./data:/app/data
